spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jdbc:
  url: jdbc:mysql://localhost:3306/sh_cars_spa
  username: sh_user
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
connection-pool:
  pool-size: 5